### ISSUE TITLE
Downloading downward

### ISSUE THREAD

**Issue by JiaxinQin0814** [Cranial-XIX/llm-pddl#2]
When I was downloading downward as the instructions in the document Assignment 1
I first clone the repository 
then run ./build.py
but  I met problem in this process
`Building configuration release.
Executing command "cmake -G Unix Makefiles -DCMAKE_BUILD_TYPE=Release ../../src" in directory "./builds/release".
-- Building for 64-bit.
CMake Error at cmake_modules/FastDownwardMacros.cmake:7 (message):
  /usr/bin/c++ does not support -std=c++20
Call Stack (most recent call first):
  cmake_modules/FastDownwardMacros.cmake:18 (check_and_set_compiler_flag)
  search/CMakeLists.txt:25 (fast_downward_set_compiler_flags)

-- Configuring incomplete, errors occurred!
See also "/home/qjx/downward/builds/release/CMakeFiles/CMakeOutput.log".
See also "/home/qjx/downward/builds/release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 145, in main
    build(config_name, CONFIGS[config_name], make_parameters)
  File "./build.py", line 121, in build
    cwd=build_path)
  File "./build.py", line 98, in try_run
    subprocess.check_call(cmd, cwd=cwd)
  File "/opt/conda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '../../src']' returned non-zero exit status 1.`

**Comment by Cranial-XIX** [comment]
Hi Jiaxin,

I compiled it locally following the instructions in that file and it seems all right. It might be that your compiler is too old, could you please try to update that and try again?

Best,
Bo

**Comment by Sbrendon98** [comment]
Hey! Jianxin, 

I got this same error on Windows, if you are using it, I would recommend switching to Linux or Mac since it compiled properly on my end. If you don't have either, and I don't recommend using wsl since you get the same issue, check your gcc version with `gcc --version`, it might be old and you can see it says "/usr/bin/c++ does not support -std=c++20" so it needs to be gcc or g++ or c++ 20, one of these. Hope this helps. Hard part is, I never got around to figuring out how to update my gcc version so if anyone has a workaround, that would be awesome.
